#ifndef RECOVERYPOINTSPLUGIN_GLOBAL_H
#define RECOVERYPOINTSPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RECOVERYPOINTSPLUGIN_LIB
# define PLUGIN_EXPORT Q_DECL_EXPORT
#else
# define PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // RECOVERYPOINTSPLUGIN_GLOBAL_H
