#ifndef SYSTEMEVENTSPLUGIN_GLOBAL_H
#define SYSTEMEVENTSPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SYSTEMEVENTSPLUGIN_LIB
# define PLUGIN_EXPORT Q_DECL_EXPORT
#else
# define PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSTEMEVENTSPLUGIN_GLOBAL_H
